name: Maven Build (Java 8)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: mvn -q -DskipTests clean package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: UltimateDonateAutomation-${{ github.sha }}
          path: |
            target/*.jar
            **/target/*.jar
